-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 14:50:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library_book_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_book_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_book_2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `library_book_2` ;

-- -----------------------------------------------------
-- Table `library_book_2`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_book_2`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL,
  `publisher` VARCHAR(20) NOT NULL,
  `author` VARCHAR(20) NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_book_2`.`library_branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_book_2`.`library_branch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(20) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_book_2`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_book_2`.`staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `library_branch_id` INT NOT NULL,
  PRIMARY KEY (`id`, `library_branch_id`),
  INDEX `fk_staff_library_branch1_idx` (`library_branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_library_branch1`
    FOREIGN KEY (`library_branch_id`)
    REFERENCES `library_book_2`.`library_branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_book_2`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_book_2`.`member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `address` VARCHAR(20) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`, `staff_id`),
  INDEX `fk_member_staff1_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `library_book_2`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_book_2`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_book_2`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total_fine` INT NOT NULL,
  `member_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`, `member_id`, `staff_id`),
  INDEX `fk_transactions_member1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_transactions_staff1_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `library_book_2`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `library_book_2`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_book_2`.`transactions_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_book_2`.`transactions_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `due_date` DATE NOT NULL,
  `return_date` DATE NOT NULL,
  `qty` INT NOT NULL,
  `fine` INT NULL DEFAULT NULL,
  `book_id` INT NOT NULL,
  `transactions_id` INT NOT NULL,
  `transactions_member_id` INT NOT NULL,
  `transactions_staff_id` INT NOT NULL,
  PRIMARY KEY (`id`, `book_id`, `transactions_id`, `transactions_member_id`, `transactions_staff_id`),
  INDEX `fk_transactions_items_book1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_transactions_items_transactions1_idx` (`transactions_id` ASC, `transactions_member_id` ASC, `transactions_staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_items_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library_book_2`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_items_transactions1`
    FOREIGN KEY (`transactions_id` , `transactions_member_id` , `transactions_staff_id`)
    REFERENCES `library_book_2`.`transactions` (`id` , `member_id` , `staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_book_2`.`shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_book_2`.`shift` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_book_2`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_book_2`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day` VARCHAR(45) NOT NULL,
  `shift_id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`, `shift_id`, `staff_id`),
  INDEX `fk_schedule_shift_idx` (`shift_id` ASC) VISIBLE,
  INDEX `fk_schedule_staff1_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_shift`
    FOREIGN KEY (`shift_id`)
    REFERENCES `library_book_2`.`shift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `library_book_2`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_book_2`.`library_branch_has_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_book_2`.`library_branch_has_book` (
  `library_branch_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `qty` INT NOT NULL,
  PRIMARY KEY (`library_branch_id`, `book_id`),
  INDEX `fk_library_branch_has_book_book1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_library_branch_has_book_library_branch1_idx` (`library_branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_library_branch_has_book_library_branch1`
    FOREIGN KEY (`library_branch_id`)
    REFERENCES `library_book_2`.`library_branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_library_branch_has_book_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library_book_2`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
